"""image_social_platform

Revision ID: 70d4ac38863b
Revises: c0dab1380db1
Create Date: 2026-07-01 22:12:26.699852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d4ac38863b'
down_revision: Union[str, None] = 'c0dab1380db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('social_platform', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_images', 'social_platform')
    # ### end Alembic commands ###
