"""image_edit_columns

Revision ID: 909229a38123
Revises: d037dfbe9111
Create Date: 2026-07-01 13:58:01.017735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909229a38123'
down_revision: Union[str, None] = 'd037dfbe9111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('source_image_id', sa.UUID(), nullable=True))
    op.add_column('generated_images', sa.Column('edit_operation', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'generated_images', 'generated_images', ['source_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.drop_column('generated_images', 'edit_operation')
    op.drop_column('generated_images', 'source_image_id')
    # ### end Alembic commands ###
