"""image_seo_columns

Revision ID: c0dab1380db1
Revises: 909229a38123
Create Date: 2026-07-01 20:01:49.035050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dab1380db1'
down_revision: Union[str, None] = '909229a38123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('alt_text', sa.Text(), nullable=True))
    op.add_column('generated_images', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('generated_images', sa.Column('seo_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_images', 'seo_filename')
    op.drop_column('generated_images', 'caption')
    op.drop_column('generated_images', 'alt_text')
    # ### end Alembic commands ###
