"""campaign operating system: brief, channels, assets, timeline, approvals, experiments, learnings

Revision ID: c7f21ab9de40
Revises: z3storeorder8
Create Date: 2026-08-07

Hand-written rather than autogenerated: autogenerate on this schema emits DROPs
for tables it cannot see, and a campaign migration is not the place to find out.

The backfill matters as much as the DDL. Existing campaigns have no slug, and a
NULL slug means "attributes no orders" -- so every existing row gets one derived
from its id, and the unique index is created only after that is done.
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "c7f21ab9de40"
down_revision = "z3storeorder8"
branch_labels = None
depends_on = None

UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    # ── campaigns: the brief, the tracking identity, the governance ──────────
    for name, col in [
        ("name", sa.Column("name", sa.String(160))),
        ("description", sa.Column("description", sa.Text())),
        ("objective", sa.Column("objective", sa.String(30))),
        ("slug", sa.Column("slug", sa.String(80))),
        ("template_key", sa.Column("template_key", sa.String(40))),
        ("product_ids", sa.Column("product_ids", sa.JSON())),
        ("collections", sa.Column("collections", sa.JSON())),
        ("audience", sa.Column("audience", sa.JSON())),
        ("offer", sa.Column("offer", sa.JSON())),
        ("budget_amount", sa.Column("budget_amount", sa.Numeric(12, 2))),
        ("budget_currency", sa.Column("budget_currency", sa.String(10))),
        ("starts_on", sa.Column("starts_on", sa.Date())),
        ("ends_on", sa.Column("ends_on", sa.Date())),
        ("primary_kpi", sa.Column("primary_kpi", sa.String(30))),
        ("secondary_kpis", sa.Column("secondary_kpis", sa.JSON())),
        ("targets", sa.Column("targets", sa.JSON())),
        ("strategy", sa.Column("strategy", sa.JSON())),
        ("brief_summary", sa.Column("brief_summary", sa.Text())),
        ("score", sa.Column("score", sa.Integer())),
        ("score_detail", sa.Column("score_detail", sa.JSON())),
        ("approval_state", sa.Column("approval_state", sa.String(20), server_default="draft", nullable=False)),
        ("approved_by", sa.Column("approved_by", UUID)),
        ("approved_at", sa.Column("approved_at", sa.DateTime(timezone=True))),
        ("autopilot", sa.Column("autopilot", sa.Boolean(), server_default=sa.text("false"), nullable=False)),
        ("launched_at", sa.Column("launched_at", sa.DateTime(timezone=True))),
    ]:
        op.add_column("campaigns", col)

    op.create_foreign_key("fk_campaigns_approved_by", "campaigns", "users",
                          ["approved_by"], ["id"], ondelete="SET NULL")

    # Old vocabulary -> new. `planned` meant "plan drafted, not yet run", which
    # is `ready`. `running`, `completed` and `failed` keep their meaning.
    op.execute("UPDATE campaigns SET status = 'ready' WHERE status = 'planned'")

    # Every existing campaign needs a tracking slug before the unique index
    # exists, or the index creation fails on duplicate NULLs-as-values later.
    # Derived from the id so it is stable and collision-free without touching
    # the goal text (which may be any language, or empty).
    op.execute("UPDATE campaigns SET slug = 'campaign-' || substr(id::text, 1, 8) WHERE slug IS NULL")

    op.create_index("ix_campaigns_project_slug", "campaigns", ["project_id", "slug"], unique=True)
    op.create_index("ix_campaigns_project_status", "campaigns", ["project_id", "status"])

    # ── channels: one row per channel execution, all sharing the campaign id ──
    op.create_table(
        "campaign_channels",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("campaign_id", UUID, sa.ForeignKey("campaigns.id", ondelete="CASCADE"), nullable=False),
        sa.Column("channel", sa.String(30), nullable=False),
        sa.Column("connector_app", sa.String(40)),
        sa.Column("status", sa.String(20), server_default="planned", nullable=False),
        sa.Column("role", sa.String(30)),
        sa.Column("budget_share", sa.Numeric(6, 2)),
        sa.Column("scheduled_at", sa.DateTime(timezone=True)),
        sa.Column("config", sa.JSON()),
        sa.Column("external_ref", sa.String(120)),
        sa.Column("last_error", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_campaign_channels_campaign", "campaign_channels", ["campaign_id"])
    op.create_index("ix_campaign_channels_scheduled", "campaign_channels", ["scheduled_at"])

    op.create_table(
        "campaign_assets",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("campaign_id", UUID, sa.ForeignKey("campaigns.id", ondelete="CASCADE"), nullable=False),
        sa.Column("channel_id", UUID, sa.ForeignKey("campaign_channels.id", ondelete="CASCADE")),
        sa.Column("kind", sa.String(30), nullable=False),
        sa.Column("variant", sa.String(4)),
        sa.Column("body", sa.Text()),
        sa.Column("image_id", UUID),
        sa.Column("meta", sa.JSON()),
        sa.Column("status", sa.String(20), server_default="draft", nullable=False),
        sa.Column("selected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_campaign_assets_campaign_kind", "campaign_assets", ["campaign_id", "kind"])

    op.create_table(
        "campaign_tasks",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("campaign_id", UUID, sa.ForeignKey("campaigns.id", ondelete="CASCADE"), nullable=False),
        sa.Column("day_offset", sa.Integer(), server_default="0", nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("detail", sa.Text()),
        sa.Column("owner", sa.String(30)),
        sa.Column("channel", sa.String(30)),
        sa.Column("status", sa.String(20), server_default="todo", nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_campaign_tasks_campaign_day", "campaign_tasks", ["campaign_id", "day_offset"])

    op.create_table(
        "campaign_approvals",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("campaign_id", UUID, sa.ForeignKey("campaigns.id", ondelete="CASCADE"), nullable=False),
        sa.Column("action", sa.String(40), nullable=False),
        sa.Column("channel_id", UUID, sa.ForeignKey("campaign_channels.id", ondelete="CASCADE")),
        sa.Column("preview", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON()),
        sa.Column("state", sa.String(20), server_default="pending", nullable=False),
        sa.Column("requested_by", UUID, sa.ForeignKey("users.id", ondelete="SET NULL")),
        sa.Column("decided_by", UUID, sa.ForeignKey("users.id", ondelete="SET NULL")),
        sa.Column("decided_at", sa.DateTime(timezone=True)),
        sa.Column("note", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_campaign_approvals_campaign_state", "campaign_approvals", ["campaign_id", "state"])

    op.create_table(
        "campaign_experiments",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("campaign_id", UUID, sa.ForeignKey("campaigns.id", ondelete="CASCADE"), nullable=False),
        sa.Column("dimension", sa.String(30), nullable=False),
        sa.Column("hypothesis", sa.Text()),
        sa.Column("variant_a_id", UUID, sa.ForeignKey("campaign_assets.id", ondelete="SET NULL")),
        sa.Column("variant_b_id", UUID, sa.ForeignKey("campaign_assets.id", ondelete="SET NULL")),
        sa.Column("metric", sa.String(30)),
        sa.Column("a_trials", sa.Integer()),
        sa.Column("a_wins", sa.Integer()),
        sa.Column("a_value", sa.Numeric(14, 2)),
        sa.Column("b_trials", sa.Integer()),
        sa.Column("b_wins", sa.Integer()),
        sa.Column("b_value", sa.Numeric(14, 2)),
        sa.Column("winner", sa.String(4)),
        sa.Column("confidence", sa.Numeric(6, 3)),
        sa.Column("revenue_impact", sa.Numeric(14, 2)),
        sa.Column("status", sa.String(20), server_default="running", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_campaign_experiments_campaign", "campaign_experiments", ["campaign_id"])

    op.create_table(
        "campaign_learnings",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("org_id", UUID, sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("project_id", UUID, sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False),
        sa.Column("campaign_id", UUID, sa.ForeignKey("campaigns.id", ondelete="SET NULL")),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON()),
        sa.Column("confidence", sa.String(10), server_default="low", nullable=False),
        sa.Column("tags", sa.JSON()),
        sa.Column("source", sa.String(20), server_default="post_campaign", nullable=False),
        sa.Column("dismissed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_campaign_learnings_project", "campaign_learnings", ["project_id"])


def downgrade() -> None:
    for t in ("campaign_learnings", "campaign_experiments", "campaign_approvals",
              "campaign_tasks", "campaign_assets", "campaign_channels"):
        op.drop_table(t)
    op.drop_index("ix_campaigns_project_status", table_name="campaigns")
    op.drop_index("ix_campaigns_project_slug", table_name="campaigns")
    op.drop_constraint("fk_campaigns_approved_by", "campaigns", type_="foreignkey")
    for c in ("launched_at", "autopilot", "approved_at", "approved_by", "approval_state",
              "score_detail", "score", "brief_summary", "strategy", "targets",
              "secondary_kpis", "primary_kpi", "ends_on", "starts_on", "budget_currency",
              "budget_amount", "offer", "audience", "collections", "product_ids",
              "template_key", "slug", "objective", "description", "name"):
        op.drop_column("campaigns", c)
    op.execute("UPDATE campaigns SET status = 'planned' WHERE status = 'ready'")
