"""brand_kit

Revision ID: d037dfbe9111
Revises: m1a2b3c4d5e6
Create Date: 2026-07-01 09:14:16.763522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd037dfbe9111'
down_revision: Union[str, None] = 'm1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'brand_kits',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('org_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('logo_url', sa.Text(), nullable=True),
        sa.Column('colors', sa.JSON(), nullable=False, server_default='[]'),
        sa.Column('primary_font', sa.String(length=100), nullable=True),
        sa.Column('secondary_font', sa.String(length=100), nullable=True),
        sa.Column('style_rules', sa.Text(), nullable=True),
        sa.Column('tone', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('org_id', name='uq_brand_kit_org'),
    )
    op.drop_index(op.f('ix_analytics_snapshots_project_date'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_provider'), table_name='api_keys')
    op.drop_index(op.f('ix_article_revisions_article_id'), table_name='article_revisions')
    op.drop_index(op.f('ix_articles_org_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_project_id'), table_name='articles')
    op.drop_index(op.f('ix_backlink_opportunities_project_status'), table_name='backlink_opportunities')
    op.drop_index(op.f('ix_backlinks_is_spam'), table_name='backlinks')
    op.drop_index(op.f('ix_backlinks_project_id'), table_name='backlinks')
    op.drop_index(op.f('ix_brand_voice_sources_brand_voice_id'), table_name='brand_voice_sources')
    op.drop_index(op.f('ix_brand_voice_sources_org_id'), table_name='brand_voice_sources')
    op.drop_index(op.f('ix_brand_voices_org_id'), table_name='brand_voices')
    op.drop_index(op.f('ix_exchange_messages_request'), table_name='exchange_messages')
    op.drop_index(op.f('ix_exchange_requests_requester'), table_name='exchange_requests')
    op.drop_index(op.f('ix_exchange_requests_target'), table_name='exchange_requests')
    op.drop_index(op.f('ix_generated_images_org_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_project_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_status'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_usage'), table_name='generated_images')
    op.drop_index(op.f('ix_keyword_rankings_keyword_date'), table_name='keyword_rankings')
    op.drop_index(op.f('ix_keyword_rankings_project_date'), table_name='keyword_rankings')
    op.drop_index(op.f('ix_org_invites_org_id'), table_name='org_invites')
    op.create_unique_constraint(None, 'org_usage', ['org_id', 'period_start'])
    op.alter_column('organizations', 'trial_ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('organizations', 'plan_locked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_publish_jobs_connection_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_org_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_project_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publishing_connections_org_id'), table_name='publishing_connections')
    op.drop_index(op.f('ix_publishing_connections_project_id'), table_name='publishing_connections')
    op.drop_index(op.f('ix_social_connections_org_id'), table_name='social_connections')
    op.drop_index(op.f('ix_social_posts_org_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_project_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_status'), table_name='social_posts')
    op.drop_index(op.f('ix_sub_events_org_id'), table_name='subscription_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_kits')
    op.create_index(op.f('ix_sub_events_org_id'), 'subscription_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_social_posts_status'), 'social_posts', ['status'], unique=False)
    op.create_index(op.f('ix_social_posts_project_id'), 'social_posts', ['project_id'], unique=False)
    op.create_index(op.f('ix_social_posts_platform'), 'social_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_posts_org_id'), 'social_posts', ['org_id'], unique=False)
    op.create_index(op.f('ix_social_connections_org_id'), 'social_connections', ['org_id'], unique=False)
    op.create_index(op.f('ix_publishing_connections_project_id'), 'publishing_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_publishing_connections_org_id'), 'publishing_connections', ['org_id'], unique=False)
    op.create_index(op.f('ix_publish_jobs_project_id'), 'publish_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_publish_jobs_org_id'), 'publish_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_publish_jobs_connection_id'), 'publish_jobs', ['connection_id'], unique=False)
    op.alter_column('organizations', 'plan_locked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('organizations', 'trial_ends_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'org_usage', type_='unique')
    op.create_index(op.f('ix_org_invites_org_id'), 'org_invites', ['org_id'], unique=False)
    op.create_index(op.f('ix_keyword_rankings_project_date'), 'keyword_rankings', ['project_id', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('ix_keyword_rankings_keyword_date'), 'keyword_rankings', ['keyword_id', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('ix_generated_images_usage'), 'generated_images', ['usage'], unique=False)
    op.create_index(op.f('ix_generated_images_status'), 'generated_images', ['status'], unique=False)
    op.create_index(op.f('ix_generated_images_project_id'), 'generated_images', ['project_id'], unique=False)
    op.create_index(op.f('ix_generated_images_org_id'), 'generated_images', ['org_id'], unique=False)
    op.create_index(op.f('ix_exchange_requests_target'), 'exchange_requests', ['target_project_id'], unique=False)
    op.create_index(op.f('ix_exchange_requests_requester'), 'exchange_requests', ['requester_project_id'], unique=False)
    op.create_index(op.f('ix_exchange_messages_request'), 'exchange_messages', ['request_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_brand_voices_org_id'), 'brand_voices', ['org_id'], unique=False)
    op.create_index(op.f('ix_brand_voice_sources_org_id'), 'brand_voice_sources', ['org_id'], unique=False)
    op.create_index(op.f('ix_brand_voice_sources_brand_voice_id'), 'brand_voice_sources', ['brand_voice_id'], unique=False)
    op.create_index(op.f('ix_backlinks_project_id'), 'backlinks', ['project_id'], unique=False)
    op.create_index(op.f('ix_backlinks_is_spam'), 'backlinks', ['project_id', 'is_spam'], unique=False)
    op.create_index(op.f('ix_backlink_opportunities_project_status'), 'backlink_opportunities', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_articles_project_id'), 'articles', ['project_id'], unique=False)
    op.create_index(op.f('ix_articles_org_id'), 'articles', ['org_id'], unique=False)
    op.create_index(op.f('ix_article_revisions_article_id'), 'article_revisions', ['article_id'], unique=False)
    op.create_index(op.f('ix_api_keys_provider'), 'api_keys', ['provider'], unique=False)
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_project_date'), 'analytics_snapshots', ['project_id', sa.literal_column('date DESC')], unique=False)
    # ### end Alembic commands ###
